spring:
    profiles:
    active:
    - dev:
---
spring:
    profiles: dev
    application:
        name: microservicecloud-config-haibin-dev
---
spring:
    profiles: test  #测试环境
    application: 
        name: microservicecloud-config-haibin-test
#   请保持为UTF-8格式